services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: greenx_db
      POSTGRES_USER: greenx_user
      POSTGRES_PASSWORD: greenx_pass
    ports:
      - "5432:5432"
