# Generated by Django 5.2 on 2025-05-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_energyoffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energyoffer',
            old_name='energy',
            new_name='energy_id',
        ),
    ]
